language: node_js
node_js:
  - "10.16.0"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ytmjatai/library-client:latest .
  - docker push ytmjatai/library-client:latest

